def greeting(name):
 print('Hello,'+name)

def EvenOdd(a):
    if(a % 2 == 0):
        print("ENTERED NUMBER IS EVEN:")
    else:
        print("ENTERED NUMBER IS ODD:")


def square(a):
    b=a*a
    print(b)


def cube(a):
    b=a*a*a
    print(b)

    
def div(a,b):
     c=a/b
     print(c)

def table(num):
    for i in range(1, 11):
        print(num, 'x', i, '=', num*i)


